---
name: Sanity tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - stable-*

jobs:
  sanity:
    uses: GomathiselviS/github_actions/.github/workflows/sanity.yml@fix_typo
